on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npx playwright install-deps
      - run: npm ci
      - run: npm run lint
      - run: npm run check-formatting
      - run: npm test
      - run: npm run test:playwright
