on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: £{{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "ably-mapbox-demo"
          heroku_email: heroku@ably.io
          procfile: "web: cd examples/subscribing-example-app && npm ci && npm start"
